emit:
  - "@typespec/http-server-csharp"
  - "@typespec/http-server-javascript"
  - "@typespec/http-client-csharp"
options:
  "@typespec/http-server-javascript":
    emitter-output-dir: "{project-root}/../servers/js/generated"
  "@typespec/http-server-csharp":
    emitter-output-dir: "{project-root}/../servers/aspnet/generated"
  "@typespec/http-client-csharp":
    emitter-output-dir: "{project-root}/../clients/dotnet"
